window.jQuery = require('jquery')
window.angular = require('angular')

// require('bootstrap')
require('angular-aria')
require('angular-animate')
require('angular-material')
require('angular-messages')
require('angular-ui-router')
require('angular-cookies')
require('angular-resource')
require('angular-sanitize')
require('angular-easyfb')
require('ng-quill')

require('quill')
require('quill/dist/quill.bubble.css')
require('quill/dist/quill.core.css')
require('quill/dist/quill.snow.css')

require('angular-material/angular-material.css')

require('bootstrap/dist/css/bootstrap.css')

require("../css/styles.css")
require("../css/session.css")
require("../css/header.css")
require("../css/list.css")
require("../css/article.css")
require("../css/new-post.css")
require("../css/login.css")
require("../css/footer.css")
require("../css/newPost.css")
